services:
  npp_deals-db:
    image: postgres:13
    environment:
      POSTGRES_DB: npp_deals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "26,Sheetpans!"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  npp_deals-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - npp_deals-db
  npp_deals-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - npp_deals-backend
volumes:
  db_data:
