version: '3.3'

services:
  npp_deals-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 26,Sheetpans!
      POSTGRES_DB: npp_deals
      TZ: America/New_York
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: npp_deals_npp_deals-db-1
  npp_deals-backend:
    build: ./backend
    environment:
      DB_NAME: npp_deals
      DB_USER: postgres
      DB_PASSWORD: 26,Sheetpans!
      DB_HOST: npp_deals-db
      DB_PORT: 5432
      SECRET_KEY: a-very-strong-secret-key
      TZ: America/New_York
    ports:
      - "8000:8000"
    depends_on:
      - npp_deals-db
    container_name: npp_deals_npp_deals-backend-1
  npp_deals-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_FRONTEND_URL: http://104.131.49.141:8000
    environment:
      TZ: America/New_York
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - npp_deals-backend
    container_name: npp_deals_npp_deals-frontend-1
volumes:
  pgdata:
