services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: npp_deals-backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: npp_deals-frontend
    ports:
      - "80:80"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: npp_deals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "26,Sheetpans!"
    volumes:
      - npp_deals_pgdata:/var/lib/postgresql/data

volumes:
  npp_deals_pgdata:
