services:
  npp_deals-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 26,Sheetpans!
      POSTGRES_DB: npp_deals
    volumes:
      - pgdata:/var/lib/postgresql/data
  npp_deals-backend:
    build: ./backend
    environment:
      DB_NAME: npp_deals
      DB_USER: postgres
      DB_PASSWORD: 26,Sheetpans!
      DB_HOST: npp_deals-db
      DB_PORT: 5432
      SECRET_KEY: a-very-strong-secret-key
    ports:
      - "8000:8000"
    depends_on:
      - npp_deals-db
  npp_deals-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_FRONTEND_URL: http://159.65.184.143:8000
    ports:
      - "80:80"
    depends_on:
      - npp_deals-backend
volumes:
  pgdata: